package com.hp.workpath.pkgmgt.util.utilities

import com.hp.workpath.pkgmgt.util.models.hpk.HPKVersion
import com.hp.workpath.pkgmgt.util.models.hpk.WorkpathPlatformVersion
import java.text.SimpleDateFormat
import java.util.*

// HPKTool version

const val TOOL_BUILD_DATE = "20260616"
const val TOOL_VERSION = "2.0-beta10.0+D20260616"

// HPKTool settings
const val SUB_APPLICATION_MAX = 5
const val ACCESSORIES_MAX = 10
val LATEST_HPK_VERSION = HPKVersion.HPK_1_4
val LATEST_PLATFORM_VERSION = WorkpathPlatformVersion.WORKPATH_PLATFORM_31_8
const val EXTERNAL_PROCESS_TIMEOUT = 60L

// connection wait 30 * 5 = 150 sec
const val CONNECTION_TRIES_MAX = 30
const val CONNECTION_TRIES_DELAY = 5000L

// Solution manifest
const val MANIFEST_ARCHIVE_VERSION = "2.0.0"
const val ASSETS_CONFIGS = "/assets/configs/"
const val ASSETS_ICONS = "/assets/icons/"
const val DEFAULT_CONFIG_KEY = "default_config"
const val DEFAULT_CONFIG_MIME = "application/json"
const val APPLICATION_TITLE_STRING_ID = "application_title"
const val APPLICATION_DESCRIPTION_STRING_ID = "application_description"
const val AUTHENTICATION_TITLE_STRING_ID = "authentication_title"
const val AUTHENTICATION_DESCRIPTION_STRING_ID = "authentication_description"
const val ACCESSORIES_NAME = "_accessories"
const val ACCESSORIES_TITLE_STRING_ID = "accessories_title"
const val ACCESSORIES_DESCRIPTION_STRING_ID = "accessories_description"
const val COPY_AGENT_NAME = "_copyAgent"
const val COPY_AGENT_TITLE_STRING_ID = "copyAgent_title"
const val COPY_AGENT_DESCRIPTION_STRING_ID = "copyAgent_description"
const val PRINT_AGENT_NAME = "_printAgent"
const val PRINT_AGENT_TITLE_STRING_ID = "printAgent_title"
const val PRINT_AGENT_DESCRIPTION_STRING_ID = "printAgent_description"
const val SCAN_AGENT_NAME = "_scanAgent"
const val SCAN_AGENT_TITLE_STRING_ID = "scanAgent_title"
const val SCAN_AGENT_DESCRIPTION_STRING_ID = "scanAgent_description"
const val DEVICE_USAGE_AGENT_NAME = "_deviceUsageAgent"
const val DEVICE_USAGE_AGENT_TITLE_STRING_ID = "deviceUsageAgent_title"
const val DEVICE_USAGE_AGENT_DESCRIPTION_STRING_ID = "deviceUsageAgent_description"
const val SUPPLIES_AGENT_NAME = "_suppliesAgent"
const val SUPPLIES_AGENT_TITLE_STRING_ID = "suppliesAgent_title"
const val SUPPLIES_AGENT_DESCRIPTION_STRING_ID = "suppliesAgent_description"
const val SECURITY_AGENT_NAME = "_securityAgent"
const val SECURITY_AGENT_TITLE_STRING_ID = "securityAgent_title"
const val SECURITY_AGENT_DESCRIPTION_STRING_ID = "securityAgent_description"
const val STATISTICS_AGENT_NAME="_statisticsJobAgent"
const val STATISTICS_AGENT_TITLE_STRING_ID="statisticsJobAgent_description"
const val STATISTICS_AGENT_DESCRIPTION_STRING_ID="statisticsJobAgent_description"
const val SOLUTION_DIAGNOSTICS_AGENT_NAME="_solutionDiagnosticsAgent"
const val SOLUTION_DIAGNOSTICS_AGENT_TITLE_STRING_ID="solutionDiagnostics_title"
const val SOLUTION_DIAGNOSTICS_AGENT_DESCRIPTION_STRING_ID="solutionDiagnostics_description"
const val MESSAGE_CENTER_AGENT_NAME="_messageCenterAgent"
const val MESSAGE_CENTER_AGENT_TITLE_STRING_ID="messageCenter_title"
const val MESSAGE_CENTER_AGENT_DESCRIPTION_STRING_ID="messageCenter_description"
const val DIRECTORY_STAGE = "stage"
const val MANIFEST_FILE_NAME = "solution.json"
const val APK_EXTENSION = "apk"
const val HPK_EXTENSION = "hpk"
const val BDL_EXTENSION = "bdl"
const val HPK2_EXTENSION = "hpk2"
const val PEM_EXTENSION = "pem"
const val JSON_EXTENSION = "json"
const val LANGUAGE_TAG_EN_US = "en-US"

// Hpk xml
const val HPK_NAMESPACE = "http://www.hp.com/schemas/jetadvantage/link/hpk/"
const val HPK_XSD = "hpk.xsd"
val DATE_FORMAT = SimpleDateFormat("yyyyMMdd", Locale.US)
const val PROVIDER_TYPE_AUTHENTICATION = "AUTHN"
const val PROVIDER_TYPE_STATISTICS = "STATISTICS"
const val PROVIDER_TYPE_HOME_SCREEN = "HOMESCREEN"
const val PROVIDER_TYPE_ACCESSORIES = "ACCESSORIES"
const val PROVIDER_TYPE_WEBSERVICES = "WEBSERVICES"
const val ACCESSORIES_SERIAL_NUMBER_NULL = "NULL"
const val WEBSERVICE_METHOD = "method"
const val WEBSERVICE_CATEGORY = "category"
const val WEBSERVICE_ABSOLUTE_PATH = "absolutePath"
const val WEBSERVICE_AUTH_TYPE = "authType"

// Spu windows
const val DIRECTORY_SQUASH = "squash"
const val DIRECTORY_TAR = "tar"
const val DIRECTORY_PAK = "pak"
const val DIRECTORY_DUMP = "dump"
const val FILENAME_SQUASH = "solution.squash"
const val FILENAME_TAR = "solution.tar.gz"
const val FILENAME_TAR_GZ_SIG = "solution.tar.gz.sig"
const val FILENAME_PAK = "solution.pak"
const val BDL_EXTENSION_WITH_DOT = ".bdl"
const val HPK2_EXTENSION_WITH_DOT = ".hpk2"
const val TAR_GZ_EXTENSION_WITH_DOT = ".tar.gz"
const val APK_EXTENSION_WITH_DOT = ".apk"
const val SQUASH_EXTENSION_WITH_DOT = ".squash"
const val SPU_CMD_SQUASHFS = "squashfs"
const val SPU_CMD_VERITY = "verity"
const val SPU_CMD_TAR = "tar"
const val SPU_TAR_FLAG_ZXVF = "-zxvf"
const val SPU_TAR_FLAG_C = "-C"
const val SPU_CMD_SIGN_TAR = "signtar"
const val SPU_CMD_FIM_PAK = "fimpak"
const val SPU_CMD_FIM_BDL = "fimbdl"
const val SPU_CMD_FIM_DUMP = "fimdump"
const val SPU_OPT_INPUT = "-i"
const val SPU_OPT_FOLDER = "-f"
const val SPU_OPT_OUTPUT = "-o"
const val SPU_OPT_KEY = "-k"
const val SPU_OPT_VENDOR = "-v"
const val SPU_OPT_NAME = "-n"
const val SPU_OPT_DESCRIPTION = "-d"
const val SPU_OPT_VERSION = "-r"
const val SPU_OPT_ID = "--id"
const val SPU_OPT_TYPE = "-t"
const val SPU_TYPE_UNVERIFIED = "unverified"
const val SPU_TYPE_RESTRICTED = "restricted"
const val SPU_TYPE_UNRESTRICTED = "unrestricted"
const val SPU_OPT_SERIAL = "--serial"
const val SPU_OPT_EMAIL = "--email"
const val SPU_OPT_PHONE = "--phone"
const val SPU_OPT_URL = "--url"
const val SPU_OPT_EXTRACT = "-x"
const val SPU_DUMP_RESULT_SERIAL_NUMBER = "SerialNumber: "
const val BUNDLE_EXTRACTOR_WSL = "wsl"
const val BUNDLE_EXTRACTOR_WSL_EXEC = "--exec"
const val SPU_DIRECTORY_COMMON = "common"
const val SPU_DIRECTORY_WINDOWS = "spu_windows"
const val SPU_EXECUTABLE_WINDOWS = "spu-cli.exe"
const val SPU_EXECUTABLE_LINUX_DLL = "spu-cli.dll"
const val SPU_RUNTIME_DOTNET = "dotnet"
const val SYSTEM_PROPERTY_USER_DIR = "user.dir"
const val SPU_PROPERTY_EXECUTABLE = "hpktool.spu.executable"
const val SPU_ENV_EXECUTABLE = "HPKTOOL_SPU_EXECUTABLE"
const val SPU_PROPERTY_HOME = "hpktool.spu.home"
const val SPU_ENV_HOME = "HPKTOOL_SPU_HOME"
const val HPKTOOL_PROPERTY_HOME_LEGACY = "hpktool.home"
const val HPKTOOL_ENV_HOME_LEGACY = "HPKTOOL_HOME"

// Command parser
const val CMD_CREATE = "create"
const val CMD_JSON = "json"
const val CMD_HELP = "help"
const val CMD_INSTALL = "install"
const val CMD_UNINSTALL = "uninstall"
const val CMD_SOLUTION_LIST = "solution-list"
const val CMD_SOLUTION_DETAIL = "solution-detail"
const val CMD_CONFIG_GET = "config-get"
const val CMD_CONFIG_UPDATE = "config-update"
const val CMD_ATTESTATION_UPDATE = "attestation-update"

const val OPT_OUTPUT = "output"
const val DESC_OPT_OUTPUT = "output directory"
const val OPT_BUILD_HPK = "build-hpk"
const val DESC_OPT_BUILD_HPK = "output.hpk"
const val OPT_SOLUTION_ID = "solution-id"
const val DESC_OPT_UUID = "UUID"
const val OPT_SOLUTION_NAME = "solution-name"
const val DESC_OPT_SOLUTION_NAME = "solution name"
const val OPT_SOLUTION_DESCRIPTION = "solution-description"
const val DESC_OPT_SOLUTION_DESCRIPTION = "solution description"
const val OPT_SOLUTION_EMAIL = "solution-email"
const val DESC_OPT_SOLUTION_EMAIL = "email"
const val OPT_SOLUTION_PHONE = "solution-phone"
const val DESC_OPT_SOLUTION_PHONE = "phone number"
const val OPT_SOLUTION_URL = "solution-url"
const val DESC_OPT_SOLUTION_URL = "web url"
const val OPT_SOLUTION_VENDOR = "solution-vendor"
const val DESC_OPT_SOLUTION_VENDOR = "vendor"
const val OPT_SOLUTION_VERSION = "solution-version"
const val DESC_OPT_SOLUTION_VERSION = "version"
const val OPT_SOLUTION_VERSION_NUMBER = "solution-version-number"
const val DESC_OPT_SOLUTION_VERSION_NUMBER = "number"
const val OPT_SOLUTION_DATE = "solution-date"
const val DESC_OPT_SOLUTION_DATE = "yyyymmdd"
const val OPT_SOLUTION_APK = "apk"
const val DESC_OPT_SOLUTION_APK = "solution apk file"
const val OPT_SOLUTION_PLATFORM_VERSION = "platform-version"
const val DESC_OPT_SOLUTION_PLATFORM_VERSION = "target platform version"
const val OPT_SOLUTION_DEFAULT_CONFIG_FILE = "default-config"
const val DESC_OPT_SOLUTION_DEFAULT_CONFIG_FILE = "default config file"
const val OPT_SOLUTION_BUNDLE_SERIAL = "solution-bundle-serial"
const val DESC_OPT_SOLUTION_BUNDLE_SERIAL = "solution bundle serial number"
const val OPT_SOLUTION_SIGNING = "solution-signing"
const val DESC_OPT_SOLUTION_SIGNING = "Solution bundle signing key"
const val OPT_APPLICATION_ID = "application-id"
const val OPT_APPLICATION_NAME = "application-name"
const val DESC_OPT_APPLICATION_NAME = "application name"
const val OPT_APPLICATION_TARGET_PACKAGE = "application-path"
const val DESC_OPT_APPLICATION_TARGET_PACKAGE = "application platform path"
const val OPT_APPLICATION_TITLE = "application-title"
const val OPT_APPLICATION_DESCRIPTION = "application-description"
const val OPT_APPLICATION_ICON = "application-icon"
const val DESC_OPT_APPLICATION_ICON = "*.png|jpeg|jpg file"
const val OPT_APPLICATION_ICON_SET = "application-icon-set"
const val DESC_OPT_APPLICATION_ICON_SET = "{\"90x90\":\"*.png|jpeg|jpg file path\"}"
const val OPT_APPLICATION_HOME_SCREEN = "application-home"
const val OPT_APPLICATION_HOME_SCREEN_DEFAULT = "application-home-default"
const val OPT_MAIN = "-main"
const val OPT_BAR = "-"
const val OPT_AUTHENTICATION_ID = "authentication-id"
const val OPT_AUTHENTICATION_NAME = "authentication-name"
const val DESC_OPT_AUTHENTICATION_NAME = "authentication name"
const val OPT_AUTHENTICATION_TITLE = "authentication-title"
const val OPT_AUTHENTICATION_DESCRIPTION = "authentication-description"
const val OPT_AUTHENTICATION_TARGET_PACKAGE = "authentication-path"
const val DESC_OPT_AUTHENTICATION_TARGET_PACKAGE = "authentication path"
const val OPT_AUTHENTICATION_PRE_PROMPT = "authentication-pre-prompt"
const val OPT_ACCESSORIES = "accessory"
const val DESC_OPT_ACCESSORIES = "type,vendor-id,product-id,(Optional)serial-number"
const val OPT_COPY_JOB_AGENT = "copy-agent"
const val OPT_PRINT_JOB_AGENT = "print-agent"
const val OPT_SCAN_JOB_AGENT = "scan-agent"
const val OPT_DEVICE_USAGE = "device-usage"
const val OPT_SUPPLIES_AGENT = "supplies"
const val OPT_WEBSERVICE_AGENT = "webservice"
const val OPT_WEBSERVICE_TITLE = "webservice-title"
const val DESC_OPT_LOCALIZED_LANGUAGE = "{\"en-US\":\"data\"}"
const val OPT_WEBSERVICE_DESCRIPTION = "webservice-description"
const val OPT_WEBSERVICE_ENDPOINT = "webservice-endpoint"
const val DESC_OPT_WEBSERVICE_ENDPOINT = "method,category,absolutePath,authType:..."
const val OPT_INSTALL_FILE = "install-file"
const val DESC_OPT_INSTALL_FILE = "solution bundle file"
const val OPT_CONNECTOR = "manifest"
const val DESC_OPT_CONNECTOR = "json-file"
const val OPT_HOST = "host"
const val DESC_OPT_HOST = "host address"
const val OPT_PASSWORD = "password"
const val DESC_OPT_PASSWORD = "password"
const val OPT_FORCE_INSTALL = "force"
const val OPT_CONFIG_DATA = "config-data"
const val DESC_OPT_CONFIG_DATA = "{\"config\":\"data\"}"
const val OPT_ATTESTATION_NAME="username"
const val DESC_OPT_ATTESTATION_NAME = "username"
const val OPT_ATTESTATION_LDB_KEY="ldbkey"
const val DESC_ATTESTATION_LDB_KEY = "ldbkey"
const val OPT_ATTESTATION_DATA="attestation-data"
const val DESC_OPT_ATTESTATION_DATA = "{\"attestation\":\"data\"}"
const val OPT_ATTESTATION_CMD_LOC = "cmdloc"
const val DESC_ATTESTATION_CMD_LOC = "cmdloc"

// ApkParser
const val DIR_TEMP = "temp"
const val DIR_TEMP_APK = "$DIR_TEMP/apk"
const val DIR_RES = "res"
const val DIR_DRAWABLE = "drawable"
const val DIR_VALUES = "values"
const val APK_PARSER_DRAWABLE_SLASH = "drawable/"
const val APK_PARSER_STRING_SLASH = "string/"
const val APK_PARSER_STRINGS_XML = "strings.xml"
const val APK_PARSER_AT_STRING = "@string"
const val APK_PARSER_VALUES_BAR = "values-"
const val FILE_ANDROID_MANIFEST = "AndroidManifest.xml"
const val MANIFEST_APPLICATION = "application"
const val MANIFEST_META_ICON = "smartux.app.icon"
const val MANIFEST_META_TITLE = "smartux.app.title"
const val MANIFEST_META_DESCRIPTION = "smartux.app.description"
const val FILE_EXTENSION_PNG = "png"
const val FILE_EXTENSION_JPG = "jpg"
const val FILE_EXTENSION_JPEG = "jpeg"
const val ICON_TYPE_PNG = "image/png"
const val ICON_TYPE_JPG = "image/jpg"

// Connection Service
const val ACCOUNT_ADMIN = "admin"
const val RESULT_SOLUTION_ID = "Solution Id: "
const val OPERATION_RESULT = "Operation result: "

// ADB
const val ADB = "adb"
const val ADB_CMD_CONNECT = "connect"
const val ADB_OPT_SERIAL = "-s"
const val ADB_CMD_SHELL = "shell"
const val ADB_CMD_AM = "am"
const val ADB_CMD_BROADCAST = "broadcast"
const val ADB_BROADCAST_SUCCESS_MARKER = "Broadcast completed"

// OS Shell
const val OS_WINDOWS_SHELL = "cmd"
const val OS_WINDOWS_SHELL_FLAG = "/c"
const val OS_UNIX_SHELL = "sh"
const val OS_UNIX_SHELL_FLAG = "-c"
const val OS_NAME_PROPERTY = "os.name"
const val OS_NAME_WINDOWS = "windows"

// Response map keys
const val RESPONSE_KEY_STATUS = "item1"
const val RESPONSE_KEY_DATA = "item2"

// Exceptions
const val FAILED = "Failed."
const val EXCEPTION_WRONG_VALUE = "Wrong value for option - "
const val EXCEPTION_NO_APPLICATION_OR_AUTHENTICATION = "Solution must have applications or authentication"
const val EXCEPTION_IS_NOT_SUPPORT = " is not support "
const val EXCEPTION_CANT_FIND_SPU_EXECUTABLE = "Can't find solution package utility program"
const val EXCEPTION_OPERATING_SYSTEM_NOT_SUPPORTED = "This host operating system is not supported"
const val EXCEPTION_INVALID_JSON = "Invalid Json format - "

const val EXCEPTION_OUT_OF_INDEX = "Out of index"

const val EXCEPTION_NO_BOUND_DEVICE = "There is no bound device."
const val EXCEPTION_INVALID_URI = "Device network address is not a valid URI."
const val EXCEPTION_DEVICE_BUSY = "Device is busy, please try later"
const val EXCEPTION_CONNECTION_TIMEOUT = "Process time out"
const val EXCEPTION_LOGIN_FAIL = "Failed to login"
const val EXCEPTION_CONNECT_FAIL = "Failed to connect host"
const val EXCEPTION_REFRESH_GRANT_FAIL = "Failed to refresh authentication"
const val EXCEPTION_AUTH_CODE_GRANT_FAIL = "Failed to grant authorization code"
const val EXCEPTION_CAPABILITIES_GET_FAIL = "Failed to get capabilities"
const val EXCEPTION_SOLUTION_GET_FAIL = "Failed to get solution"
const val EXCEPTION_SOLUTIONS_GET_FAIL = "Failed to get solutions"
const val EXCEPTION_CONTEXT_GET_FAIL = "Failed to get solution context"
const val EXCEPTION_CONTEXT_MODIFY_FAIL = "Failed to modify solution context"
const val EXCEPTION_CONTEXT_REPLACE_FAIL = "Failed to replace solution context"
const val EXCEPTION_INSTALL_CODE_REISSUE_FAIL = "Failed to reissue install code"
const val EXCEPTION_INSTALLER_GET_FAIL = "Failed to get installer"
const val EXCEPTION_INSTALL_FAIL = "Failed to install solution"
const val EXCEPTION_UNINSTALL_FAIL = "Failed to uninstall solution"
const val EXCEPTION_INSTALLER_OPERATIONS_GET_FAIL = "Failed to get install operations"
const val EXCEPTION_INSTALLER_OPERATION_GET_FAIL = "Failed to get install operation"
const val EXCEPTION_CONFIG_GET_FAIL = "Failed to get configuration data"
const val EXCEPTION_CONFIG_UPDATE_FAIL = "Failed to update configuration data"
const val EXCEPTION_OPERATION_FAIL = "Failed to operation"

const val EXCEPTION_UNSUPPORTED_IMAGE_TYPE = "Not supported Image type"

const val EXCEPTION_HPK_OPEN_FAIL = "Failed to open hpk file"

const val EXCEPTION_LOG_SAVE_FILE = "Error while saving log file: "
const val LOG_FILE_DIRECTORY = "log"
const val LOG_FILE_DATETIME_PATTERN = "yyyy-MM-dd_HH-mm-ss.SSS"

// Localized resources
const val LANGUAGE_RESOURCE = "localizedString"
val DEFAULT_LOCALE = Locale.ENGLISH!!
val MESSAGE: ResourceBundle = ResourceBundle.getBundle(
    LANGUAGE_RESOURCE, DEFAULT_LOCALE
)
